// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTqMfpOmMXpZe_2h2wqJRoFgXnbw4m64',
    appId: '1:942920170981:android:b9bf57360feb8c33f3830c',
    messagingSenderId: '942920170981',
    projectId: 'summitgearppb',
    storageBucket: 'summitgearppb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtgNa7_UdJoLpuETRRxAHWo0xIwoh11g',
    appId: '1:942920170981:ios:cb63a9f20da7250ef3830c',
    messagingSenderId: '942920170981',
    projectId: 'summitgearppb',
    storageBucket: 'summitgearppb.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbQ4D-1x8ayA1lGS64zwB-01uiPcplKYc',
    appId: '1:942920170981:web:4979c23671de0cf9f3830c',
    messagingSenderId: '942920170981',
    projectId: 'summitgearppb',
    authDomain: 'summitgearppb.firebaseapp.com',
    storageBucket: 'summitgearppb.appspot.com',
    measurementId: 'G-R0CJFL7754',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNtgNa7_UdJoLpuETRRxAHWo0xIwoh11g',
    appId: '1:942920170981:ios:cb63a9f20da7250ef3830c',
    messagingSenderId: '942920170981',
    projectId: 'summitgearppb',
    storageBucket: 'summitgearppb.appspot.com',
    iosBundleId: 'com.example.praktikum09',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbQ4D-1x8ayA1lGS64zwB-01uiPcplKYc',
    appId: '1:942920170981:web:ef55e0823a3500f2f3830c',
    messagingSenderId: '942920170981',
    projectId: 'summitgearppb',
    authDomain: 'summitgearppb.firebaseapp.com',
    storageBucket: 'summitgearppb.appspot.com',
    measurementId: 'G-26RVN7X4X9',
  );

}